#!/bin/sh

# This script runs the SAGA logicalfile test for the generic adaptor.
# The servers are listed below, and should be replaced by your own
# servers.

GENERIC_SERVERS="$1"
case X$GENERIC_SERVERS in
    X)
	GENERIC_SERVERS=localhost,fs0.das3.cs.vu.nl
	;;
esac

export JAVA_SAGA_LOCATION=`cd .. && pwd`

$JAVA_SAGA_LOCATION/scripts/run-saga-app -Xmx256M \
    test.logicalfile.LogicalFileAdaptorTest generic $GENERIC_SERVERS
