#!/bin/sh

# This script runs the SAGA sd test for the glite adaptor.
# The server is listed below, and should be replaced by your own
# server.

export JAVA_SAGA_LOCATION=`cd .. && pwd`

host=`hostname`
infoUrl=http://rgma04.pp.rl.ac.uk:2170
$JAVA_SAGA_LOCATION/bin/run-saga-app -Xmx256M \
    test.sd.SDAdaptorTest glite $host $infoUrl
