#!/bin/sh

# This script runs the SAGA fileoutputstream test for the javagat adaptor.
# The server is listed below, and should be replaced by your own
# server.

JAVAGAT_SERVER=fs0.das3.cs.vu.nl

export SAGA_LOCATION=`cd .. && pwd`

$SAGA_LOCATION/bin/run_saga_app -Xmx256M \
    test.file.FileInputStreamAdaptorTest javagat $JAVAGAT_SERVER
