#!/bin/sh

# This script runs the SAGA fileoutputstream test for the javagat adaptor.
# The server is listed below, and should be replaced by your own
# server.

JAVAGAT_SERVER=titan.cs.vu.nl

export SAGA_LOCATION=`cd .. && pwd`

$SAGA_LOCATION/bin/run_saga_app \
    test.file.FileOutputStreamAdaptorTest javagat $JAVAGAT_SERVER
