#!/bin/sh

# This script runs the SAGA stream test for the socket and javagat adaptors.

PORT=3333

HOST=localhost

export SAGA_LOCATION=`cd .. && pwd`

$SAGA_LOCATION/bin/run_saga_app \
     test.stream.StreamAdaptorTest socket tcp://$HOST:$PORT

# $SAGA_LOCATION/bin/run_saga_app \
#      test.stream.StreamAdaptorTest javagat tcp://$HOST:$PORT
