#!/bin/sh

# This runs the SAGA gridsam adaptor (not the JavaGAT one).
# For this test, you first need to run an ftp server on port 12345.
# For instance:
#     $HOME/OMIICLIENT/gridsam/bin/gridsam-ftp-server -d $HOME/data -p 12345

. ./paths

$SAGA_LOCATION/bin/run_saga_app -DJobService.adaptor.name=gridsam test.job.TestJob1
