#!/bin/sh

# Some file manipulations within a remote directory

export SAGA_LOCATION=`cd .. && pwd`

$SAGA_LOCATION/bin/run_saga_app -Xmx256M demo.namespace.Sequence file1 file2 gsiftp://fs0.das2.cs.vu.nl/home/ceriel/testDirectory "Hello world"
