#!/bin/sh

export JAVA_SAGA_LOCATION=`cd .. && pwd`

$JAVA_SAGA_LOCATION/bin/run-saga-app -Xmx256M demo.namespace.TaskCopyTest ftp://ftp.cs.vu.nl/pub/ceriel/LLgen.tar.gz http://www.cs.vu.nl/orca/index.html
